---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2ssdsdsxddxdsddfddsdsddsdfsdasdf
kind: Deployment
metadata:
  name: httpd
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: httpd
  replicas: 3 # tells deployment to run 1 pods matching the templates
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: default
  labels:
    app: httpd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8099
  selector:
    app: httpd
  type: LoadBalancer
