---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginxtestjenkins
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginxtestjenkins
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: nginx
  type: LoadBalancer
